<?php
// Heading
$_['text_home ']    = 'Home';
$_['heading_title']    = 'Purpletree Multivendor Settings';
$_['vendor_heading']    = 'Vendor settings';
$_['order_heading']    = 'Order settings';
$_['seller_product_heading']    = 'Seller product settings';
$_['seller_review_heading']    = 'Seller review settings';
$_['seller_contact_heading']    = 'Seller contact settings';
$_['seller_email_heading']    = 'Seller email templates';
$_['seller_store_heading']    = 'Seller store options';
$_['text_hide_seller_product_tab'] = 'Use Smart Product Form';
$_['text_extension']   = 'Extensions';
$_['text_success']     = 'Success: You have modified Purpletree Multivendor settings!';
$_['text_edit']        = 'Edit Purpletree Multivendor Settings';
$_['text_yes']        = 'Yes';
$_['text_no']        = 'No';
$_['text_allowed_categories']        = 'Allow all categories';
$_['text_selected_categories']        = 'Allow selected categories';
$_['text_license_error']        = 'Your license key is invalid';
$_['text_store_seller_name']        = 'Seller name';
$_['text_store_email']        = 'Store email';
$_['text_store_phone']        = 'Store phone';
$_['text_store_address']        = 'Store address';
$_['text_seller_logedin']        = 'Logged In';
$_['text_seller_general']        = 'General';
$_['text_license_key_changed'] = 'License key has been Changed. Click on Save button to save changes';

$_['text_assign_categories']        = 'Some products assign to this category please disable them then remove.';
$_["text_seller_product_template"]        = "Use Product Templates";

////////category for sing seller product/////
$_['entry_seller_product_category'] = ' No. of categories allow for a single product';
$_['text_multiple']        = 'Multiple';
$_['text_single']        = 'Single';
/////////////////

$_['entry_commission'] = 'Commission (in percent per product sale)';
$_['entry_commission_status'] = 'Admin Status for which Commission will calculate';
$_['please_select'] = '--Please Select--';
$_['error_commission_status'] = 'This field is required!';
$_['entry_seller_manage_order'] = 'Allow seller to manage orders';
$_['entry_seller_approval'] = 'Seller approval required';
$_['entry_product_approval'] = 'Product approval required';
$_['entry_product_edit_approval'] = 'Product edit approval required';
$_['entry_allow_category'] = 'Allow category for seller';
$_['entry_become_seller'] = 'Become seller on signup page';
$_['entry_order_approval'] = 'Order approval required';
$_['entry_allow_related'] = 'Allow seller to add related product';
$_['entry_limit_purchase'] = 'Max. number of seller products allowed in cart';
$_['entry_allow_metals'] = 'Allow seller to add metals product';
$_['entry_seller_review'] = 'Seller review enabled';
$_['entry_seller_contact'] = 'Seller contact mode';
$_['entry_license']        = 'License key';
$_['entry_seller_store']        = 'Fields to show';
$_['entry_seller_invoice']        = 'Invoice/shipping generated by seller';
$_['commission_from_seller_group'] = 'Commission from seller group';
$_['entry_shipping_commission'] = 'Shipping Commission (in percent)';
$_['Commission_invoice_footer_text'] = 'Commission Invoice Footer text';

// Entry
$_['entry_status']            = 'Status';
$_['entry_order_id']          = 'Order ID';
$_['entry_email_id']          = 'Email ID';
$_['please_wait']             = 'Please wait..';

// Error
$_['error_permission'] = 'Warning: You do not have permission to modify Purpletree Multivendor Settings!';
$_['error_commission'] = 'Please enter valid commission!';
$_['error_product_limit'] = 'Please enter product limit!';
$_['error_process_data'] = 'License key is required!';
$_['error_order_id'] = 'Enter valid Order Id!';
$_['error_email_id'] = 'Enter valid e-mail address!';
$_['error_Enter_license_key'] ="Enter license key";
$_['allow_browse_sellers'] ="Enable Browse Sellers";

//button
$_['dont_have_lisence_key'] = 'Dont Have License Key'; 
$_['enter_license_key1'] = 'Enter License Key';
$_['button_get_license'] = 'Get License';
$_['button_submit'] = 'Submit';
$_['entry_allow_live_chat'] = 'Allow Tawk.to Live Chat';
$_['button_ok'] = 'OK';
$_['change_license_key'] = 'Change License Key';

//Configuration for subscription plan
$_['heading_subscription_plan']='Subscription Plan';
$_['enable_subscription_plans_txt']='Enable Subscription Plans';
$_['enable_subscription_price_txt']='Enable Subscription Fees';
$_['enable_joining_fees_txt'] ='Enable Joining Fees';
$_['paypal_hosted_button_id'] ="PayPal E-Mail ID";
$_['tax_name_txt'] ='Tax Name';
$_['tax_value_txt']='Tax Value(in percent)';///
//$_['reminder_one_enable_txt']='First Reminder Enable';
$_['reminder_one_days_before_to_be_sent_txt']='First Reminder ( in Days, 0 to disable )';
//$_['reminder_two_enable_txt']='Second Reminder Enable';
$_['reminder_two_days_before_to_be_sent_txt']='Second Reminder ( in Days, 0 to disable )';
//$_['reminder_three_enable_txt']='Third Reminder Enable';
$_['reminder_three_days_before_to_be_sent_txt']='Third Reminder ( in Days, 0 to disable )';
$_['grace_period_txt']='Grace Period';
//validation
$_['error_tax_value'] = 'Enter Valid Tax Value';
$_['error_tax_name'] = 'Enter Valid Tax Name';
$_['grace_period_error'] = 'Enter Valid Grace Period';
$_['reminder_one_days_error'] = 'Enter Valid Reminder Days';
$_['reminder_two_days_error'] = 'Enter Valid Reminder Days';
$_['reminder_three_days_error'] = 'Enter Valid Reminder Days';
$_['error_shipping_commission'] = 'Please enter valid shipping commission!';
//development option
$_['text_hide_user_menu']        = 'Hide User Menu for sellers';
$_['heading_development_Option'] = 'Development Option';
$_['enable_include_jquery']        = 'Include jQuery';
$_['text_hide_seller_product_tab'] = 'Use Smart Product Form';//hide seller product tab
$_['enable_multiple_active_plan']        = 'Enable Multiple Subscription Plans';
$_['text_store_social_link']        = 'Social Links';//social link 
/////////////////Start seller Blog setting/////////////////
$_['seller_blog_heading']    = 'Seller Blog settings';
$_['text_sort_order']    = 'Sort order';
$_['text_create_date_order']    = 'Create date';
$_['entry_seller_sort_by']    = 'Sort by';
/////////////////End  seller Blog setting/////////////////
$_['form_error_warning'] = 'Please check form carefully ';
//navbar texts
$_['text_general'] = 'General';
$_['text_seller'] = 'Seller';
$_['text_subscription'] = 'Subscription';
$_['text_other_settings'] = 'Other Settings';
$_['text_development'] = 'Development';
$_['entry_featured_enabled_hide_edit'] = 'Featured enabled hide edit button';

